import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle2, AlertTriangle, ChevronDown, ChevronUp, Info } from 'lucide-react';

interface ResultCardProps {
  result: any;
}

const ResultCard: React.FC<ResultCardProps> = ({ result }) => {
  const [expanded, setExpanded] = useState(false);

  if (!result) return null;

  const isImage = result.type === 'image';
  const isAI = isImage ? result.hasC2pa && result.producer : result.isWatermarked;
  
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full max-w-2xl mx-auto mt-8 bg-gray-900 border border-gray-700 rounded-2xl overflow-hidden shadow-xl"
    >
      <div className="p-6 border-b border-gray-800">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-4">
            <div className={`p-3 rounded-full ${isAI ? 'bg-amber-500/10 text-amber-500' : 'bg-emerald-500/10 text-emerald-500'}`}>
              {isAI ? <AlertTriangle className="w-6 h-6" /> : <CheckCircle2 className="w-6 h-6" />}
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-100">
                {isImage ? 'Image Analysis Complete' : 'Text Analysis Complete'}
              </h3>
              <p className="text-gray-400 text-sm">
                {isAI 
                  ? 'AI generation signatures detected in this content.' 
                  : 'No clear AI signatures detected. Likely human-created.'}
              </p>
            </div>
          </div>
          
          <div className="text-right">
            <div className="text-3xl font-bold text-gray-100">
              {isImage ? (isAI ? '100%' : '0%') : `${(result.score * 100).toFixed(0)}%`}
            </div>
            <div className="text-xs text-gray-500 uppercase font-semibold tracking-wider">AI Probability</div>
          </div>
        </div>
      </div>

      <div 
        className="px-6 py-3 bg-gray-800/50 flex items-center justify-between cursor-pointer hover:bg-gray-800 transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <span className="text-sm font-medium text-gray-300">View detailed breakdown</span>
        {expanded ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
      </div>

      <AnimatePresence>
        {expanded && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="p-6 pt-4 space-y-4">
              {isImage ? (
                <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                  <div className="flex items-center gap-2 mb-2 text-gray-300 font-medium">
                    <Info className="w-4 h-4 text-blue-400" /> Content Credentials (C2PA)
                  </div>
                  {result.hasC2pa ? (
                    <div className="space-y-3 mt-4">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-500">Origin / Producer</span>
                        <span className="text-gray-200 font-medium">{result.producer}</span>
                      </div>
                      <div className="border-t border-gray-700 pt-3">
                        <span className="text-gray-500 text-sm block mb-2">Detected Modifications</span>
                        <div className="flex flex-wrap gap-2">
                          {result.edits && result.edits.length > 0 ? (
                            result.edits.map((edit: any, idx: number) => (
                              <span key={idx} className="bg-gray-900 text-gray-300 text-xs px-2 py-1 rounded border border-gray-700">
                                {edit.action}
                              </span>
                            ))
                          ) : (
                            <span className="text-gray-400 text-sm">No specific edits recorded.</span>
                          )}
                        </div>
                      </div>
                    </div>
                  ) : (
                    <p className="text-gray-400 text-sm mt-2">No C2PA manifest found. The image metadata has been stripped or it was not generated by a compliant AI tool.</p>
                  )}
                </div>
              ) : (
                <div className="bg-gray-800 p-4 rounded-lg border border-gray-700">
                  <div className="flex items-center gap-2 mb-2 text-gray-300 font-medium">
                    <Info className="w-4 h-4 text-blue-400" /> SynthID Watermark
                  </div>
                  <p className="text-gray-400 text-sm mb-4">
                    DeepMind's SynthID analyzes the statistical distribution of the text tokens to identify hidden watermark patterns.
                  </p>
                  <div className="flex justify-between items-center text-sm">
                    <span className="text-gray-500">Weighted Mean Score</span>
                    <span className="text-gray-200 font-mono bg-gray-900 px-2 py-1 rounded">{result.score.toFixed(4)}</span>
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default ResultCard;
